name: 20 Daily Auto-Commits

on:
  schedule:
    - cron: '0 0 * * *'   # Every day at 00:00 UTC
  workflow_dispatch:       # Allow manual run

jobs:
  spam-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run 20 auto-commits
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          for i in $(seq 1 20); do
            echo "Auto commit $i on $(date)" >> data.txt
            git add data.txt
            git commit -m "🤖 Auto commit $i - $(date)"
            sleep 1
          done

          git push
